<?php
/**
 * @file
 * Views Fiters Selective Module
 */

/**
 * Implements hook_views_api().
 */
function views_filters_selective_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Implements hook_views_filters_selective_handler().
 */
function views_filters_selective_views_filters_selective_handler() {
  return array(
    'views_handler_filter' => 'views_filters_selective_handler_filter',
  );
}

/**
 * Callback implementation for generic filter.
 */
function views_filters_selective_handler_filter($filter, $oids) {
  $options = array();
  foreach ($oids as $id) {
    $options[] = $id;
  }
  return $options;
}
